version: '3.8'

services:
  db:
    image: mysql:8.2
    container_name: database
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DB=${MYSQL_DB} 
    ports:
      - "3306:3306"
    networks:
      - backend
    volumes:
      - db_data:/var/lib/mysql
    restart: always
  frontend: 
    container_name: frontend
    build: ./Frontend/retrosync-preprod
    volumes:
      - ./Frontend/retrosync-preprod/src:/code/src
      - /project/node_modules
    ports:
      - "3000:3000"
    networks:
      - frontend
    environment:
      NODE_ENV: development
    tty: true
    command: npm start
    restart: on-failure:3
  api:
    build: ./API
    container_name: apiserver
    ports:
      - "80:80"
    volumes:
      - ./API:/code
    env_file:
      - .env
    networks:
      - backend
    restart: on-failure:3
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
volumes:
  db_data: